### ISSUE TITLE
Server crash on start

### ISSUE THREAD

**Issue by ehamawy** [repulica/customcommands#2]
Latest fabric and fabric api as of 12/4/2021
MC 1.18 JDK-17
Same error with and without fabric-permissions-api-v0.1.jar installed
Same error with github releases tab and build from sauce

`Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[21:55:32] [INFO] [FabricLoader/GameProvider]: Loading for game Minecraft 1.18
[21:55:33] [main/INFO]: Loading for game Minecraft 1.18
[21:55:33] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:188) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) [fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.8.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.8.jar:?]
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
        at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:121) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:121) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:202) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:186) ~[fabric-loader-0.12.8.jar:?]
        ... 8 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing C:\pathtomyserverfolder\mods\customcommands-1.1.0.jar: net.fabricmc.loader.impl.util.ExceptionUtil$WrappedException: net.fabricmc.loader.impl.metadata.ParseMetadataException: Error reading fabric.mod.json file for mod at C:\pathtomyserverfolder\mods\customcommands-1.1.0.jar -> META-INF/jars/kdl4j-0.1.0.jar: Failed to parse version
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562) ~[?:?]
        at java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604) ~[?:?]
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981) ~[?:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:118) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:202) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:186) ~[fabric-loader-0.12.8.jar:?]
        ... 8 more
Caused by: java.lang.RuntimeException: Error analyzing C:\pathtomyserverfolder\mods\customcommands-1.1.0.jar: net.fabricmc.loader.impl.util.ExceptionUtil$WrappedException: net.fabricmc.loader.impl.metadata.ParseMetadataException: Error reading fabric.mod.json file for mod at C:\pathtomyserverfolder\mods\customcommands-1.1.0.jar -> META-INF/jars/kdl4j-0.1.0.jar: Failed to parse version
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:210) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:167) ~[fabric-loader-0.12.8.jar:?]
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: net.fabricmc.loader.impl.util.ExceptionUtil$WrappedException: net.fabricmc.loader.impl.metadata.ParseMetadataException: Error reading fabric.mod.json file for mod at C:\pathtomyserverfolder\mods\customcommands-1.1.0.jar -> META-INF/jars/kdl4j-0.1.0.jar: Failed to parse version
        at net.fabricmc.loader.impl.util.ExceptionUtil.wrap(ExceptionUtil.java:51) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:196) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:167) ~[fabric-loader-0.12.8.jar:?]
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686) ~[?:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeNestedMods(ModDiscoverer.java:408) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:250) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:205) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:167) ~[fabric-loader-0.12.8.jar:?]
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: net.fabricmc.loader.impl.metadata.ParseMetadataException: Error reading fabric.mod.json file for mod at C:\pathtomyserverfolder\mods\customcommands-1.1.0.jar -> META-INF/jars/kdl4j-0.1.0.jar: Failed to parse version
        at net.fabricmc.loader.impl.metadata.V1ModMetadataParser.parse(V1ModMetadataParser.java:120) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.metadata.ModMetadataParser.readModMetadata(ModMetadataParser.java:160) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.metadata.ModMetadataParser.readModMetadata(ModMetadataParser.java:123) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.metadata.ModMetadataParser.parseMetadata(ModMetadataParser.java:52) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarStream(ModDiscoverer.java:304) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:194) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:167) ~[fabric-loader-0.12.8.jar:?]
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686) ~[?:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeNestedMods(ModDiscoverer.java:408) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:250) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:205) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:167) ~[fabric-loader-0.12.8.jar:?]
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: net.fabricmc.loader.api.VersionParsingException: Version must be a non-empty string!
        at net.fabricmc.loader.impl.util.version.VersionParser.parse(VersionParser.java:26) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.metadata.V1ModMetadataParser.parse(V1ModMetadataParser.java:118) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.metadata.ModMetadataParser.readModMetadata(ModMetadataParser.java:160) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.metadata.ModMetadataParser.readModMetadata(ModMetadataParser.java:123) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.metadata.ModMetadataParser.parseMetadata(ModMetadataParser.java:52) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarStream(ModDiscoverer.java:304) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:194) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:167) ~[fabric-loader-0.12.8.jar:?]
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686) ~[?:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeNestedMods(ModDiscoverer.java:408) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:250) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:205) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:167) ~[fabric-loader-0.12.8.jar:?]
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]`

**Comment by repulica** [comment]
what the heck

**Comment by repulica** [comment]
oh it looks like a parse error with include for kdl4j i dont quite know what to do about that

ill look into possibilities
